import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("algae_data.csv")
print("Dataset:\n", data)
correlation = data.corr()
print("\nCorrelation with Algae:\n")
print(correlation["Algae"])
plt.scatter(data["Temp"], data["Algae"])
plt.xlabel("Temperature")
plt.ylabel("Algae Growth")
plt.title("Temperature vs Algae Growth")
plt.show()
plt.scatter(data["Nutrients"], data["Algae"])
plt.xlabel("Nutrients")
plt.ylabel("Algae Growth")
plt.title("Nutrients vs Algae Growth")
plt.show()
most_impact = correlation["Algae"].drop("Algae").idxmax()
print("\nMost impactful factor:", most_impact)